### ISSUE TITLE
Slowing gem

### ISSUE THREAD

**Issue by peterfarge** [gemforce-team/gemforce#5]
Why there are no receipts for slowing gems?
In this [tutorial](https://armorgames.com/community/thread/12479126/gemcraft-cs-extreme-end-game-guide-v11) from 12345ieee is a slowing gem with blue+red+black. Is it the same receipt like the mana specs, except I replace the orange with the blue gem?

**Comment by 12345ieee** [comment]
There are no recipes for slowing gems because slow% is capped (at 90).
This cap is really easy to reach, by the time you are using non-standard combines (WL 2k+) your BlBR gem can reach the cap at g7 even with simple U.
Considering you have to get it to g30-35 for the speed cap, you are absolutely certain you'll get the slow% to cap as well.

So, in short, there are no recipes because it doesn't help, you'd only lose time for no benefit.

**Comment by peterfarge** [comment]
Thanks for the answer :)
So, a 50% blue, 50% black and a little red will do the job.

**Comment by 12345ieee** [comment]
Yeah, any reasonable proportion will do the job.
Closing the issue,
