### ISSUE TITLE
Waiting for the new tool for FW

### ISSUE THREAD

**Issue by Sraw** [gemforce-team/gemforce#7]
This is a wonderful tool for the CS, is there any new version for FW too?

**Comment by 12345ieee** [comment]
Gem combination follows optimal endgame tactics.

Once our tacticians, mostly located at [the GC Discord](https://discord.gg/afstnfY) have done figuring out what gems are useful, combines will be computed for them.

Then hopefully someone will update this tool to work with GCFW, as its layout is different.

**Comment by Sraw** [comment]
Good news! But it sounds like you won't update the tool anymore?

**Comment by 12345ieee** [comment]
The whole GC tooling is made of many programs, I'll keep working on other, but I will indeed not maintain this one anymore.

**Comment by Sraw** [comment]
Thanks for all the efforts :)

**Comment by 12345ieee** [comment]
I thought this issue was in the wGC repo, not this one.
I will keep working on this, it's wGC that I'll stop supporting.

I have updated my comments to reflect that, sorry for the misunderstanding @Sraw .

We're getting a better idea of the tactics needed for GSFW, I'm closing this, new developments will be announced where they'll be ready.
